### PR TITLE
Fix flaky detection of source path caused by VS Code flipping the case of drive letters sometimes

### LINKED ISSUE #442: For some modules, you get a warning about an incorrect sourc path, even though other siblings are fine.
**Describe the bug**
image

even thouh `salix::canvas::Demo` is fine.

**To Reproduce**

open `salix-contrib` and go to `salix/canvas/Heart.rsc`

### PR DESCRIPTION
**Pull request by DavyLandman**
Fixes #442

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -7,10 +7,10 @@ extra_flags=''
 clean="clean"
 while getopts 'fd' flag; do
   case "${flag}" in
-    f) extra_flags='-Drascal.compile.skip -Drascal.tutor.skip' ;;
+    f) extra_flags='-Drascal.compile.skip -Drascal.tutor.skip -DskipTests' ;;
```
Comment (toinehartman) [inline build.sh:10]: Are these changes committed intentionally?

**Review by toinehartman — APPROVED** [review]
LGTM. Thanks for this fix! I think I ran into this a couple of times and it's pretty annoying.

File: build.sh (hunk 1 above)
Comment (DavyLandman) [reply build.sh:10]: yes, but primarily since I didn't want to have a separate PR just for that addition.
