### PR TITLE
Path config-less summaries for stdlib

### LINKED ISSUE #1048: Path config-less summary computation for library modules
**Describe the bug**

Currently, summary computation requires a path config. Path configs are only applicable to source projects, so for library projects, this is confusing and might introduce errors.

Change summary computation for library modules to not compute path configs.

Preparing work on Rascal: https://github.com/usethesource/rascal/pull/2748
Related issues:
- https://github.com/usethesource/rascal/issues/2743
- https://github.com/usethesource/rascal-language-servers/issues/968

**To Reproduce**

1. Open a module with stdlib imports.
2. Trigger a type-check.
3. Go-to-def on `import IO` (or similar)
4. In the opened standrad library module, go-to-def on some reference again.
5. Observe the path config in the debug console; it has a project root in `std://`, `jar+file://` or `mvn://`

**Expected behavior**
Do not compute a path config for binary modules.

**Desktop (please complete the following information):**
 - Context: VS Code extension
 - Rascal Version: LSP `2.22.3`

### PR DESCRIPTION
**Pull request by toinehartman**
Closes #1048

### CODE REVIEW

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java [hunk 1]
```diff
@@ -130,19 +132,60 @@ public RascalLanguageServices(RascalTextDocumentService docService, BaseWorkspac
         this.workspaceService = workspaceService;
     }
 
-    public InterruptibleFuture<@Nullable IConstructor> getSummary(ISourceLocation occ, PathConfig pcfg) {
+    private String pathToModuleName(ISourceLocation l) {
+        var p = l.getPath();
+        return p.substring(1, p.lastIndexOf('.')).replaceAll("/", "::");
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java]: I agree, use `replace` that already does all, but doesn't parse the search string as a regex.

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java [hunk 2]
```diff
@@ -130,19 +132,60 @@ public RascalLanguageServices(RascalTextDocumentService docService, BaseWorkspac
...
+                    var modTplDir = URIUtil.getChildLocation(URIUtil.changePath(modPath, "rascal"), modPrefix);
+                    return URIUtil.getChildLocation(modTplDir, tplFileName);
+                }
+                case "std": {
+                    var stdResolved = Locations.toPhysicalIfPossible(modPath);
+                    if ("jar+file".equals(stdResolved.getScheme())) {
+                        var stdJarRoot = URIUtil.changePath(stdResolved, stdResolved.getPath().substring(0, stdResolved.getPath().lastIndexOf('!') + 1));
+                        var modTplDir = URIUtil.getChildLocation(URIUtil.getChildLocation(stdJarRoot, "rascal"), modPrefix);
+                        return URIUtil.getChildLocation(modTplDir, tplFileName);
+                    }
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java]: add comment for intended fall-through

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java [hunk 3]
```diff
@@ -130,19 +132,60 @@ public RascalLanguageServices(RascalTextDocumentService docService, BaseWorkspac
...
-            IString moduleName = VF.string(pcfg.getModuleName(occ));
-            return runEvaluator("Rascal makeSummary", semanticEvaluator, eval -> {
-                IConstructor result = (IConstructor) eval.call("makeSummary", moduleName, pcfg.asConstructor());
-                return result != null && result.asWithKeywordParameters().hasParameters() ? result : null;
-            }, null, exec, false, client);
-        } catch (IOException e) {
-            logger.error("Error looking up module name from source location {}", occ, e);
-            return InterruptibleFuture.completedFuture(null, exec);
+            var tplFileName = "$" + URIUtil.getLocationName(URIUtil.changeExtension(modPath, "tpl"));
+            var modPrefix = URIUtil.getParentLocation(modPath).getPath();
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java]: these two can be merged, it avoids the double `getChildLocation` on both branches

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java [hunk 4]
```diff
@@ -130,19 +132,60 @@ public RascalLanguageServices(RascalTextDocumentService docService, BaseWorkspac
...
+            switch (modPath.getScheme()) {
+                case "jar+file": // intentional fall-through
+                case "mvn": {
+                    var modTplDir = URIUtil.getChildLocation(URIUtil.changePath(modPath, "rascal"), modPrefix);
+                    return URIUtil.getChildLocation(modTplDir, tplFileName);
+                }
+                case "std": {
+                    var stdResolved = Locations.toPhysicalIfPossible(modPath);
+                    if ("jar+file".equals(stdResolved.getScheme())) {
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java]: what if std resolved to `mvn`?

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java [hunk 5]
```diff
@@ -130,19 +132,60 @@ public RascalLanguageServices(RascalTextDocumentService docService, BaseWorkspac
...
-            }, null, exec, false, client);
-        } catch (IOException e) {
-            logger.error("Error looking up module name from source location {}", occ, e);
-            return InterruptibleFuture.completedFuture(null, exec);
+            var tplFileName = "$" + URIUtil.getLocationName(URIUtil.changeExtension(modPath, "tpl"));
+            var modPrefix = URIUtil.getParentLocation(modPath).getPath();
+            switch (modPath.getScheme()) {
+                case "jar+file": // intentional fall-through
+                case "mvn": {
+                    var modTplDir = URIUtil.getChildLocation(URIUtil.changePath(modPath, "rascal"), modPrefix);
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java]: is this correct for `jar+file`? doesn't this remove the `!` part?

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java [hunk 6]
```diff
@@ -130,19 +132,60 @@ public RascalLanguageServices(RascalTextDocumentService docService, BaseWorkspac
...
+                    return URIUtil.getChildLocation(modTplDir, tplFileName);
+                }
+                case "std": {
+                    var stdResolved = Locations.toPhysicalIfPossible(modPath);
+                    if ("jar+file".equals(stdResolved.getScheme())) {
+                        var stdJarRoot = URIUtil.changePath(stdResolved, stdResolved.getPath().substring(0, stdResolved.getPath().lastIndexOf('!') + 1));
+                        var modTplDir = URIUtil.getChildLocation(URIUtil.getChildLocation(stdJarRoot, "rascal"), modPrefix);
+                        return URIUtil.getChildLocation(modTplDir, tplFileName);
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java]: I think this should be the case for `jar+file` and then after resolving it, we call ourselves (with a custom param for the module root).

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java [hunk 7]
```diff
@@ -130,19 +132,60 @@ public RascalLanguageServices(RascalTextDocumentService docService, BaseWorkspac
...
     }
 
+    public InterruptibleFuture<@Nullable IConstructor> getSummary(ISourceLocation occ, Function<ISourceLocation, PathConfig> computePathConfig) {
+        Function<Evaluator, IConstructor> computeSummary;
+        var tplLoc = libTplLoc(occ);
+        if (tplLoc != null) {
+            computeSummary = eval -> (IConstructor) eval.call("makeSummary", VF.string(pathToModuleName(occ)), tplLoc);
+        } else {
+            try {
+                var pcfg = computePathConfig.apply(occ);
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java]: this calculation should be done inside the completable future (so moved inside of the `eval ->` part)

**Review by DavyLandman — CHANGES_REQUESTED** [review]
Some small changes, especially for the case of the `jar+file`

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java [hunk 8]
```diff
@@ -130,17 +132,98 @@ public RascalLanguageServices(RascalTextDocumentService docService, BaseWorkspac
...
         try {
-            IString moduleName = VF.string(pcfg.getModuleName(occ));
-            return runEvaluator("Rascal makeSummary", semanticEvaluator, eval -> {
-                IConstructor result = (IConstructor) eval.call("makeSummary", moduleName, pcfg.asConstructor());
-                return result != null && result.asWithKeywordParameters().hasParameters() ? result : null;
-            }, null, exec, false, client);
-        } catch (IOException e) {
-            logger.error("Error looking up module name from source location {}", occ, e);
-            return InterruptibleFuture.completedFuture(null, exec);
+            var tplFolder = libraryTplRoot(modPath);
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java:149]: yes, this is nice 👍🏼

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java [hunk 9]
```diff
@@ -130,17 +132,98 @@ public RascalLanguageServices(RascalTextDocumentService docService, BaseWorkspac
...
+        if ("jar+file".equals(modPath.getScheme())) {
+            // For a file within a JAR, return the sub-path within the JAR
+            return jarFilePath(modPath);
+        }
+        // Otherwise, return just the sub-path
+        return modPath.getPath();
+    }
+
+    private static ISourceLocation jarBasePath(ISourceLocation l) throws URISyntaxException {
+        if (!"jar+file".equals(l.getScheme())) {
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/rascal/RascalLanguageServices.java]: in principle we should see `l.getScheme().startsWith("jar+")` as it should behave the same for anything under it. for example `jar+home` or `jar+project` all we care about is that we're looking in a jar.

(this is true for all the cases that match `jar+file`)

**Review by DavyLandman — CHANGES_REQUESTED** [review]
Looks fine, except we can be a bit more defensive and not just support `jar+file` but any  `jar+` scheme.

**Review by DavyLandman — APPROVED** [review]
