### PR TITLE
Semantic tokenizer improvements: tests, simplification, syntax-in-syntax bugfix

### LINKED ISSUE #456: Semantic tokenizer makes mistakes when a `syntax` tree (with category) has `syntax` children
**Describe the bug**

Imagine a grammar of the following shape:

```rascal
syntax FooBarWithCategory = @category="string" FooBar;
syntax FooBar             = "foo" "bar";
```

The semantic tokenizer will not tokenize input `"foo bar"` to a token with category `string`.

**To Reproduce**

Define the following function:

```
void f() {
    int  x = 3;
    real y = 3.14;
    rat  z = 3/14;
}
```

**Expected behavior**

  - Expected: `3`,`3.14`, and `3r14` are highlighted as numbers
  - Actual: `3` isn't highlighted

**Screenshots**

image

**Additional context**

The current Rascal [grammar](https://github.com/usethesource/rascal/blob/main/src/org/rascalmpl/library/lang/rascal/syntax/Rascal.rsc) doesn't include categories for [literals](https://github.com/usethesource/rascal/blob/0c2d864828bbbb978f92701d138e888c26bbde2e/src/org/rascalmpl/library/lang/rascal/syntax/Rascal.rsc#L21-L30), but this absence is ["patched"](https://github.com/usethesource/rascal-language-servers/blob/6162e0c39484b1c452e2f0bfc548694258a3873e/rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/util/SemanticTokenizer.java#L460-L464) inside the semantic tokenizer, so each `int`, `real`, and `rat` should be tokenized as a [number](https://github.com/usethesource/rascal-language-servers/blob/6162e0c39484b1c452e2f0bfc548694258a3873e/rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/util/SemanticTokenizer.java#L583-L586). As a result, effectively, the semantic tokenizer works with the following grammar:

```rascal
syntax Literal
    = @category="number" integer:  IntegerLiteral  integerLiteral 
    | @category="number" \real:    RealLiteral     realLiteral 
    | @category="number" rational: RationalLiteral rationalLiteral
    | ...
    ;

syntax  IntegerLiteral  = ...
lexical RealLiteral     = ...
lexical RationalLiteral = ...
```

`IntegerLiteral` does fit the shape above ("Describe the bug"), while `RealLiteral` and `RationalLiteral` don't: `IntegerLiteral` is `syntax`-in-`syntax`, while `RealLiteral`/`RationalLiteral` are `lexical`-in-`syntax`. The precise place in the code that causes the difference in tokenization behavior is this:

https://github.com/usethesource/rascal-language-servers/blob/6162e0c39484b1c452e2f0bfc548694258a3873e/rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/util/SemanticTokenizer.java#L468-L469

https://github.com/usethesource/rascal-language-servers/blob/6162e0c39484b1c452e2f0bfc548694258a3873e/rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/util/SemanticTokenizer.java#L473-L475

### PR DESCRIPTION
**Pull request by sungshik**
This PR:

  - adds tests for the semantic tokenizer;
  - removes duplicate logic for computing maximal tokens;
  - fixes #456.

Before this PR:

image

After this PR:

image

See this history for details:

  - #494
  - #500
  - ~~#501~~ (replaced by <span>#</span>502)
  - #502
  - 69ab630

### CODE REVIEW

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/util/SemanticTokenizerTester.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+        var tokens = new IValue[encoded.size() / 5];
+        var tokenTypes = tokenizer.capabilities().getTokenTypes();
+
+        for (int i = 0; i < encoded.size(); i += 5) {
+            var deltaLine     = values.integer(encoded.get(i));
+            var deltaStart    = values.integer(encoded.get(i + 1));
+            var length        = values.integer(encoded.get(i + 2));
+            var tokenType     = values.string(tokenTypes.get(encoded.get(i + 3)));
+            var tokenModifier = values.string(""); // Token modifiers aren't supported yet
+            tokens[i / 5] = values.tuple(deltaLine, deltaStart, length, tokenType, tokenModifier);
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/util/SemanticTokenizerTester.java:52]: nit: we  normally use list writers and append on them, instead of keeping this array around.

Comment (sungshik) [reply rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/util/SemanticTokenizerTester.java]: Ah, thanks, I didn't realize. The writer even has `appendTuple` 🙂

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/LanguageContributionsMultiplexer.java [hunk 2]
```diff
@@ -159,6 +161,8 @@ private synchronized void calculateRouting() {
         hasReferences = anyTrue(ILanguageContributions::hasReferences);
         hasImplementation = anyTrue(ILanguageContributions::hasImplementation);
 
+        specialCaseHighlighting = anyTrue(ILanguageContributions::specialCaseHighlighting);
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/LanguageContributionsMultiplexer.java:164]: for the parser we do something special, we say `firstOrFail` can we do something similar here as well? so that we only pickup the parsing status from the first contribution?

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/util/SemanticTokenizerTester.java [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+import io.usethesource.vallang.IConstructor;
+import io.usethesource.vallang.IValue;
+
+public class SemanticTokenizerTester {
+
+    public IValue toTokens(IConstructor tree, IBool useSpecialCaseHighlighting, IBool applyRascalCategoryPatch) {
+        var tokenizer = new SemanticTokenizer(applyRascalCategoryPatch.getValue());
+        var encoded = tokenizer.semanticTokensFull((ITree) tree, useSpecialCaseHighlighting.getValue()).getData();
+
+        var values = IRascalValueFactory.getInstance();
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/util/SemanticTokenizerTester.java:42]: a rascal library function should get the value factory injected in the constructor of the class.

File: rascal-lsp/src/main/rascal/lang/rascal/tests/semanticTokenizer/Util.rsc [hunk 4]
```diff
@@ -0,0 +1,175 @@
...
+    = [a | Actual a: <<_, _, _, tokenType, _>, _, _> <- actuals];
+
+private list[Actual] filterByString(list[Actual] actuals, str string)
+    = [a | a <- actuals, contains(a.s, string)];
+
+//
+// Expects
+//
+
+data Expect // Represents...
```
Comment (DavyLandman) [inline rascal-lsp/src/main/rascal/lang/rascal/tests/semanticTokenizer/Util.rsc:141]: nit: newline after this one is a bit unexpected?

File: rascal-lsp/src/main/rascal/lang/rascal/tests/semanticTokenizer/Util.rsc [hunk 5]
```diff
@@ -0,0 +1,175 @@
...
+
+    // ...the expectation that the `n`-th/first/last occurrence of `string` is
+    // in a token of type `tokenType`
+    = expectNth(int n, str string, str tokenType)
+    | expectFirst(str string, str tokenType)
+    | expectLast(str string, str tokenType)
+
+    // ...the expectation that each occurrence of `string` is not in a token of
+    // type `tokenType`
+    | expectEachNot(str string, str tokenType);
```
Comment (DavyLandman) [inline rascal-lsp/src/main/rascal/lang/rascal/tests/semanticTokenizer/Util.rsc:151]: nit: normally for a multiline adt we put the `;` on the next line.

File: rascal-lsp/src/main/rascal/lang/rascal/tests/semanticTokenizer/Util.rsc [hunk 6]
```diff
@@ -0,0 +1,175 @@
...
+//
+// Length conversion: Characters are counted as 16-bit units in LSP, whereas
+// they are counted as 32-bit units in Rascal, so lengths need to be converted.
+// The difference manifests only in the presence of surrogate pairs.
+//
+
+alias Length32 = int;
+alias Length16 = int;
+
+private Length32 toLength32(Length16 n16, str input) {
```
Comment (DavyLandman) [inline rascal-lsp/src/main/rascal/lang/rascal/tests/semanticTokenizer/Util.rsc:106]: I'm very happy we have tests, but a bit sad we have to write all of this.

File: rascal-vscode-extension/src/lsp/ParameterizedLanguageServer.ts [hunk 7]
```diff
@@ -183,7 +183,8 @@ export interface ParserSpecification {
     nonTerminalIsStart?: boolean;
     /** allow ambiguities during parsing, default: false */
     allowAmbiguity?: boolean;
-
+    /** apply the special case for highlighting syntax-in-syntax, default: true */
```
Comment (DavyLandman) [inline rascal-vscode-extension/src/lsp/ParameterizedLanguageServer.ts:186]: maybe also add the warning here that it will get replaced soon.

**Review by DavyLandman — CHANGES_REQUESTED** [review]
Looks good, a few small things I noticed.

File: rascal-lsp/src/main/rascal/lang/rascal/tests/semanticTokenizer/Util.rsc (hunk 6 above)
Comment (sungshik) [reply rascal-lsp/src/main/rascal/lang/rascal/tests/semanticTokenizer/Util.rsc:106]: Agreed...

**Review by DavyLandman — APPROVED** [review]
LGTM, I also checked with @jurgenvinju and he also approves of the change to the `parsing` constructor.
