### PR TITLE
Diagnostics of extension-less files are cleared

### LINKED ISSUE #1058: Diagnostics of extension-less files aren't cleared
**Describe the bug**

Diagnostics of extension-less files aren't cleared.

**To Reproduce (Manual)**

Steps:

 1. Open a Rascal terminal, import the language server of Pico (`import demo::lang::pico::LanguageServer;`), and register it (`main()`).
 2. Create and open an extension-less file.
 3. Run command "Change Language Mode" and select "Parametric Rascal LSP". An error diagnostic is reported.
 4. Close the file. The error diagnostic is still in the Problems view. **(A)**
 5. Delete the file. The error diagnostic is still in the Problems view. **(B)**

Issues:

  - **A:** I wonder if the error diagnostic should have been cleared after step 3.
      - It shouldn't have: The file still exists.
      - It should have: The file isn't in language mode "Parametric Rascal LSP" anymore (as witnessed by the fact that, upon reopening, the language mode has reverted to "Plain Text").
  - **B:** The error diagnostic should have been cleared after step 4. 

**To Reproduce (UI Tests)**

To reproduce in UI tests, the following could be added to `afterEach` in `dsl.test.ts` to check if all error diagnostics have been cleared:

https://github.com/usethesource/rascal-language-servers/blob/6033ab06bc4027e4ac8c00e43c7ef7f93204cb67/rascal-vscode-extension/src/test/vscode-suite/dsl.test.ts#L97-L103

```ts
// Add after line 102:
const bottomBar = bench.getBottomBar();
const problemsView = await bottomBar.openProblemsView();
const allVisibleMarkers = await problemsView.getAllVisibleMarkers(MarkerType.Error);
expect(allVisibleMarkers.length, "Not all error diagnostics have been cleared").to.equal(0);
```

With this addition, the UI tests fail:
```
  1) DSL+recovery
       "after each" hook for "has syntax highlighting in documents without extension":

      Not all error diagnostics have been cleared
      + expected - actual

      -1
      +0
```

(In general, the addition isn't perfect yet, as it checks only the "visible" diagnostics, so if scrolling down past a large number of warnings is needed to find the first error, then that error is missed and the check mistakenly succeeds. For all current tests, though, I think this works fine.)

### PR DESCRIPTION
**Pull request by sungshik**
This PR fixes #1058. It doesn't add UI tests yet, because diagnostics cannot be reliably counted until #1065 is fixed.

With help from @toinehartman.

clear-diagnostics-extension-less-file

### CODE REVIEW

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/BaseWorkspaceService.java [hunk 1]
```diff
@@ -91,6 +99,16 @@ public void initialize(ClientCapabilities clientCap, @Nullable List<WorkspaceFol
...
         }
+
+        // Make sure that all delete events are listened to by this workspace service (and propagated to the linked
+        // document service by method `didDeleteFiles`), so all diagnostics of deleted files can be properly cleared.
+        var fileOperationCapabilities = Nullables.ensureNonNullAndGet(workspaceCapabilities, WorkspaceServerCapabilities::getFileOperations, WorkspaceServerCapabilities::setFileOperations, FileOperationsServerCapabilities::new);
+        if (Nullables.has(clientCap.getWorkspace(), WorkspaceClientCapabilities::getFileOperations, FileOperationsWorkspaceCapabilities::getDidDelete)) {
+            var anyFile = new FileOperationPattern("**/*");
+            anyFile.setMatches(FileOperationPatternKind.File);
+            var didDelete = new FileOperationOptions(Stream.of(anyFile).map(FileOperationFilter::new).collect(Collectors.toList()));
+            fileOperationCapabilities.setDidDelete(didDelete);
```
Comment (toinehartman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/BaseWorkspaceService.java]: I don't think is correct, since for parametric, we set this capability dynamically here: https://github.com/usethesource/rascal-language-servers/blob/45c839a5406c2265becc1fe910e3e0e91942db88/rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/ParametricTextDocumentService.java#L265-L268

Setting the same capability statically and dynamically is not allowed ([LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#client_registerCapability)).

**Review by toinehartman — CHANGES_REQUESTED** [review]
I believe we need to do this registration dynamically instead of statically.

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/capabilities/FileOperationCapability.java [hunk 2]
```diff
@@ -84,6 +84,11 @@ protected final FileOperationOptions mergeOptions(FileOperationOptions o1, FileO
         anyFolder.setMatches(FileOperationPatternKind.Folder);
         patterns.add(new FileOperationFilter(anyFolder));
 
+        // Only extension-less files would be enough, but it seems that cannot be expressed using LSP's glob patterns.
```
Comment (sungshik) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/capabilities/FileOperationCapability.java]: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#workspace_willCreateFiles

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/BaseWorkspaceService.java (hunk 1 above)
Comment (sungshik) [reply rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/BaseWorkspaceService.java]: Thanks! Updated the PR as discussed in the call, except it seems LSP's glob patterns cannot express extension-less files.

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/capabilities/FileOperationCapability.java (hunk 2 above)
Comment (toinehartman) [reply rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/capabilities/FileOperationCapability.java]: Can we not do `**/[!.-.]`? ([source](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#fileOperationPattern))

Comment (sungshik) [reply rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/capabilities/FileOperationCapability.java]: Nope, `[!.-.]` matches only a single character, so this pattern matches `foo/b`, but not `foo/ba`.

**Review by toinehartman — APPROVED** [review]

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/capabilities/FileOperationCapability.java [hunk 3]
```diff
@@ -84,6 +84,11 @@ protected final FileOperationOptions mergeOptions(FileOperationOptions o1, FileO
...
+        var anyFile = new FileOperationPattern("**/*");
+        anyFile.setMatches(FileOperationPatternKind.File);
+        patterns.add(new FileOperationFilter(anyFile));
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/capabilities/FileOperationCapability.java]: Can we limit the file operation to only fire for deletes? and not all events?
