### PR TITLE
Remember files opened as `Parametric Rascal LSP` before language registration

### LINKED ISSUE #795: If a DSL file is already open when it's registered, the user gets a whole lot of error messages
**Describe the bug**

After a restart VS Code remembers that a file was a "Rascal DSL" file, so it starts seinding it to the parametric server.

This shows the user a whole bunch of errors:

Image

stack trace:

```
/d:/swat.engineering/projects/sidn/bird/bird-core/bird-src/nesting_and_cycles2.bird
2025-09-29 13:32:45.436 [info] [Error - 1:32:45 PM] Request textDocument/documentSymbol failed.
2025-09-29 13:32:45.436 [info]   Message: Unknown file: |file:///d:/swat.engineering/projects/sidn/bird/bird-core/bird-src/nesting_and_cycles2.bird|
  Code: -32803 
/d:/swat.engineering/projects/sidn/bird/bird-core/bird-src/nesting_and_cycles2.bird
2025-09-29 13:32:45.444 [info] [Error - 1:32:45 PM] Request textDocument/foldingRange failed.
2025-09-29 13:32:45.444 [info]   Message: Unknown file: |file:///d:/swat.engineering/projects/sidn/bird/bird-core/bird-src/nesting_and_cycles2.bird|
  Code: -32803 
/d:/swat.engineering/projects/sidn/bird/bird-core/bird-src/nesting_and_cycles2.bird
2025-09-29 13:32:45.445 [info] [Error - 1:32:45 PM] Request textDocument/semanticTokens/full failed.
2025-09-29 13:32:45.445 [info]   Message: Unknown file: |file:///d:/swat.engineering/projects/sidn/bird/bird-core/bird-src/nesting_and_cycles2.bird|
  Code: -32803 
/d:/swat.engineering/projects/sidn/bird
```

**To Reproduce**

1. before register language, open a dsl file, and manually change the file type to `Parametric Rascal LSP`
2. register the language
3. open the file.
4. lot's of error pop up

After this we can never recover, since we got no "didOpen" event for an extension that we support, so we dropped it, but all subsequent events get dropped too, so perhaps we should be a bit less picky about which events we drop in the parametric server, as it might be a race between the register language and the current state.

**Expected behavior**
- We should pickup changes that come in even if we missed the `didOpen`
- File that are already open should be supported in LSP

**Stack traces**

```

/d:/swat.engineering/projects/sidn/bird/bird-core/bird-src/nesting_and_cycles2.bird
2025-09-29 13:34:11.283 [warning] [parametric-1] org.eclipse.lsp4j.jsonrpc.RemoteEndpoint Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "textDocument/didChange",
  "params": {
    "textDocument": {
      "version": 2,
      "uri": "file:///d%3A/swat.engineering/projects/sidn/bird/bird-core/bird-src/nesting_and_cycles2.bird"
    },
    "contentChanges": [
      {
        "text": "module nesting_and_cycles2\n\nstruct Node {\n    u8 a\n    u8 b\n}\n\nchoice Loop(Node n) {\n    struct {\n        u8 _ ?(\u003d\u003d\"0\")\n    }\n    struct {\n        u8 aRef ?(\u003d\u003dn.a)\n        Node n1 ?(n1.a \u003d\u003d n.b) // the .b of this one is free\n        Node n2 ?(n2.a \u003d\u003d n1.b) // the .b of this one is free\n        Loop l(n1)\n    }\n}\n\n\nstruct Start {\n    u8 header ?(\u003d\u003d\"H\")\n    Node initial\n    Loop loop(initial)\n}\n\n\n// example input:\n// Hcdcdeefdeggh0 (nesting_and_cycles_test2.txt)\n// Start(initial \u003d Node(c,d),\n//       loop \u003d Loop(\n//              aRef \u003d c, \n//              n1 \u003d Node(d, e), \n//              n2 \u003d Node(e, f), \n//              l \u003d Loop(\n//                   aRef \u003d d, \n//                   n1 \u003d Node(e, g),\n//                   n2 \u003d Node(g, h),\n//                   l \u003d Loop(_ \u003d 0)\n//              )                \n//      )) \n"
      }
    ]
  }
} org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unknown file: |file:///d:/swat.engineering/projects/sidn/bird/bird-core/bird-src/nesting_and_cycles2.bird|
	at org.rascalmpl.vscode.lsp.parametric.ParametricTextDocumentService.getFile(ParametricTextDocumentService.java:652)
	at org.rascalmpl.vscode.lsp.parametric.ParametricTextDocumentService.getFile(ParametricTextDocumentService.java:646)
	at org.rascalmpl.vscode.lsp.parametric.ParametricTextDocumentService.updateContents(ParametricTextDocumentService.java:345)
	at org.rascalmpl.vscode.lsp.parametric.ParametricTextDocumentService.didChange(ParametricTextDocumentService.java:290)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:160)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:231)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:198)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Desktop (please complete the following information):**
Based on: https://github.com/usethesource/rascal-language-servers/actions/runs/18044376262

**Additional context**
This used to work

### PR DESCRIPTION
**Pull request by toinehartman**
This PR keeps track of files that are open with language `Parametric Rascal LSP`, for which there is no language registered yet. Once the user registers a language, we update the associated open editors.

This PR closes #795.

### CODE REVIEW

**Review by DavyLandman — CHANGES_REQUESTED** [review]
I think this PR is a bit involved, as in it requires many places to take into account possible race between registry & availability of the language. Especially if someone later adds a new capability, it'll soon be forgotten.

I'm thinking there might be a way to make a subclass of our ParsingOnlyContribution (like `EmptyContribution`) and then connect that to the incoming file. and when a registry comes in, we update all the existing mappings to the new contribution?

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/TextDocumentState.java [hunk 1]
```diff
@@ -81,6 +81,11 @@ public TextDocumentState(
         this.last = new AtomicReference<>();
     }
 
+    public void setParser(BiFunction<ISourceLocation, String, CompletableFuture<ITree>> parser) {
+        this.parser = parser;
```
[the remark this answers is not in the document]
Comment (DavyLandman) [reply rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/TextDocumentState.java:85]: It might be wiser to make a new `TextDocumentState` that inherits some of the fields? like an upgrade/clone or something? With the new parser configured. Since what does it mean to switch the parser, but not the resolved parse trees etc?

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/ParametricTextDocumentService.java [hunk 2]
```diff
@@ -327,12 +328,19 @@ public void didDeleteFiles(DeleteFilesParams params) {
...
     }
+
     private void triggerAnalyzer(VersionedTextDocumentIdentifier doc, Duration delay) {
-        logger.trace("Triggering analyzer for {}", doc.getUri());
         var location = Locations.toLoc(doc);
+        triggerAnalyzer(location, doc.getVersion(), delay);
+    }
+
+    private void triggerAnalyzer(ISourceLocation location, int version, Duration delay) {
+        logger.trace("Triggering analyzer for {}", location);
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/ParametricTextDocumentService.java:338]: this log should be inside the if, and an else branch that logs why we're not triggering an analyzer?

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/ParametricTextDocumentService.java [hunk 3]
```diff
@@ -597,38 +605,53 @@ private static <T> T last(List<T> l) {
...
     private TextDocumentState open(TextDocumentItem doc, long timestamp) {
-        return files.computeIfAbsent(Locations.toLoc(doc),
-            l -> new TextDocumentState(contributions(l)::parsing, l, doc.getVersion(), doc.getText(), timestamp)
-        );
+        var loc = Locations.toLoc(doc);
+        BiFunction<ISourceLocation, String, CompletableFuture<ITree>> parser
+            = isLanguageRegistered(loc)
+            ? contributions(loc)::parsing
+            // Language not (yet) registered; plug in an incomplete parse future
+            : (l, s) -> new CompletableFuture<>();
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/ParametricTextDocumentService.java:651]: this future will never complete, won't that cause issues? like any down stream jobs?

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/ParametricTextDocumentService.java [hunk 4]
```diff
@@ -851,6 +874,21 @@ public synchronized void registerLanguage(LanguageParameter lang) {
...
+
+        // If we opened any files with this extension before, now associate them with contributions
+        var extensions = Arrays.asList(lang.getExtensions());
+        for (var e : files.entrySet()) {
+            var f = e.getKey();
+            var state = e.getValue();
+            if (extensions.contains(extension(f))) {
+                logger.trace("Open file of language {} - updating state: {}", lang.getName(), f);
+                var c = state.getCurrentContent();
+                state = files.replace(f, new TextDocumentState(contributions(f)::parsing, f, c.version(), state.getCurrentContent().get(), state.getLastModified()));
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/ParametricTextDocumentService.java:886]: I think we should have a function on `TextDocumentState`  called `changeParser` or something, such that it can be responsible for passing on the right state to the new instance?

**Review by DavyLandman — APPROVED** [review]
I like how small this got in the end.

**Review by DavyLandman — CHANGES_REQUESTED** [review]
This doesn't feel complete to me, or else I'm missing some connections.

**Review by DavyLandman — COMMENTED** [review]
Yes, this is much better, I have some small questions and stuff we need to improve.

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/NoContributions.java [hunk 5]
```diff
@@ -0,0 +1,263 @@
...
+
+    @Override
+    public CompletableFuture<Boolean> hasSelectionRange() {
+        return falseFut;
+    }
+
+    @Override
+    public CompletableFuture<Boolean> specialCaseHighlighting() {
+        return falseFut;
+    }
```
[the remark this answers is not in the document]
Comment (toinehartman) [reply rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/NoContributions.java]: Done

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/ParametricTextDocumentService.java [hunk 6]
```diff
@@ -611,44 +622,52 @@ private static <T> T last(List<T> l) {
...
+        return fact;
     }
 
     private TextDocumentState open(TextDocumentItem doc, long timestamp) {
-        return files.computeIfAbsent(Locations.toLoc(doc),
-            l -> new TextDocumentState(contributions(l)::parsing, l, doc.getVersion(), doc.getText(), timestamp)
-        );
+        var loc = Locations.toLoc(doc);
+        return files.computeIfAbsent(loc,
+            l -> new TextDocumentState(contributions(loc)::parsing, l, doc.getVersion(), doc.getText(), timestamp));
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/parametric/ParametricTextDocumentService.java]: `l` and `loc` are the same, no need to capture them from outside the closure.

(I don't see why we need this change?)

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/TextDocumentState.java [hunk 7]
```diff
@@ -195,26 +196,33 @@ public CompletableFuture<Versioned<List<Diagnostics.Template>>> getDiagnosticsAs
...
-                    // Complete future to get diagnostics
-                    var diagnostics = new Versioned<>(version, diagnosticsList);
-                    diagnosticsAsync.complete(diagnostics);
-                });
+                        // Complete future to get diagnostics
+                        var diagnostics = new Versioned<>(version, diagnosticsList);
+                        diagnosticsAsync.complete(diagnostics);
+                    });
+            } catch (NoContributionException e) {
+                logger.debug("Ignoring missing parser for {}", location, e);
```
Comment (DavyLandman) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/TextDocumentState.java]: Is it no problem that treeAsync is never completed?

**Review by DavyLandman — CHANGES_REQUESTED** [review]
Two small questions, for the rest it looks find

**Review by DavyLandman — APPROVED** [review]
