### PR TITLE
Fix rascal hovers showing random types

### LINKED ISSUE #260: Hover help in Rascal file displays seemingly random data
**Describe the bug**

image

This shows the hover help of a "randomly" different constructor. This is not due to the previous dirty summary bug, this
one is always random.

### PR DESCRIPTION
**Pull request by DavyLandman**
Fixes #260

As discussed, there were 3 bugs:

1. We were registering offset from different modules as part of our own module (rascal-core (c/s)hould maybe filter that?)
2. We were merging (with random results) overlapping offsets to a single value
3. After fixing 2, I found that we also didn't correctly support overlapping ranges.

This PR fixes all 3, where I'm a bit sad I have to walk the whole tree, but that seems inevitable.

### CODE REVIEW

**Comment by PaulKlint** [comment]
Indeed the summary should filter locations outside current module.

**Comment by jurgenvinju** [comment]
Which tree are we walking? I can't find that code in the source. Can you point me to it @DavyLandman ? Typically in the eclipse version of this functionality, we'd use the cursor offset in the file to find a path in the tree to all relevant source locations, in `log(n)` time where n is the size of the file.

File: rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/util/locations/impl/TreeMapLookup.java [hunk 1]
```diff
@@ -101,12 +101,18 @@ private static boolean rangeContains(Range a, Range b) {
...
     public @Nullable T lookup(Range from) {
-        T result = contains(data.floorEntry(from), from);
-        if (result == null) {
-            // could be that it's at the start of the entry
-            result = contains(data.ceilingEntry(from), from);
+        // since we allow for overlapping ranges, it might be that we have to
+        // search all the way to the "bottom" of the tree to see if we are
+        // contained in something larger than the closest key
+        var previousKeys = data.headMap(from, true).descendingMap();
+        for (var candidate : previousKeys.entrySet()) {
```
Comment (jurgenvinju) [inline rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/util/locations/impl/TreeMapLookup.java:108]: I'd rather read the type of `candidate` here instead of `var`. I'm getting lost. Same for `previousKeys`.

**Comment by DavyLandman** [comment]
> Which tree are we walking? I can't find that code in the source. Can you point me to it @DavyLandman ? Typically in the eclipse version of this functionality, we'd use the cursor offset in the file to find a path in the tree to all relevant source locations, in `log(n)` time where n is the size of the file.

The `TreeMap` in the `TreeMapLookup` class. We don't have a parse-tree here (we just have a binary rel). So we use the R-B tree inside TreeMap, but yesterday I was thinking that if we would build our own tree (RB or not) it might make it "faster" to iterate it.

**Comment by jurgenvinju** [comment]
I think we might separate the (fuzzy) search from the translation; if we use the parse Tree to provide a (list of) candidate source locations, then these ranges can be translated one-to-one to the LSP Range concept. There is no need to walk over the entire data-structure anymore, and the lookup would be twice in log time, once log of the size of the input file and once log the size of the lookup cache. WDYT?

**Comment by DavyLandman** [comment]
Sounds like a new PR :) This is fixing the bug we have right now.

I don't exactly understand your proposal. We get a summary from the rascal-core with just a few rels in there, do you want to put it back in a parse tree?

I was thinking we could build a specific RB tree to do a some better mapping of this logic, but for now using TreeMaps are good enough. It just could be faster.

**Comment by DavyLandman** [comment]
Ah, thanks for explaining that in a bit more detail.

**Comment by DavyLandman** [comment]
I've added a random test that tries to fill the TreeMap with all kinds of ranges (trying to cram lots of overlapping ranges in there) and then made sure the specific range would still be found. 

I propose we go ahead with this, and think of a different approach at a later point. As in, it's primarily a performance discussion after this right?

**Comment by jurgenvinju** [comment]
I'm testing the fixes:
* hover help and jump-to-definition within a file works fine
* hover help between files _seems_ to work (but I don't know if I'm missing more information)
* jump-to-definition to another file *never* works (@DavyLandman this is interesting)
* the hovered type of any field is equal to the type of the container instead of the field. I.e. `graph.to` would show `Graph[int]` instead of `omt`.

**Comment by jurgenvinju** [comment]
Ok, I'm retracting the jump-to-definition bug:
> /Users/hillsma/Projects/rascal/pico-analysis/src/main/rascal/lang/pico/Abstract.rsc

So this was an older .tpl file in my target folder that got unzipped.

It is an instance of #242 ; at least if we would have used `project` URL's where possible, this would not have happened. 

* jump-to-definition works now
